import { jsPDF } from "jspdf";
import type {
  AgentIteration,
  ApprovalRequest,
  EvidenceItem,
  ExecutionEvent,
  RunSummary,
  TaskSummary,
  ToolInvocation
} from "./api";
import { budgetRowsFromIteration } from "./agent";
import { STATE_LABEL, toExecutionState } from "./status";
import { buildReportFilename, sanitizeReportText } from "./sanitizeText";

export type ExecutionReportActor = {
  display_name: string;
  email: string;
};

/**
 * Everything the report is built from — deliberately the same shape the UI
 * already fetched and displayed for this actor. There is no separate fetch
 * path here, so the export can never see more than the screen already did.
 */
export type ExecutionReportInput = {
  actor: ExecutionReportActor | null;
  run: RunSummary;
  tasks: TaskSummary[];
  events: ExecutionEvent[];
  toolInvocations: ToolInvocation[];
  evidenceItems: EvidenceItem[];
  approvals: ApprovalRequest[];
  agentIterations: AgentIteration[];
  generatedAt?: Date;
};

const MARGIN = 48;
const PAGE_WIDTH = 612; // US Letter, points
const PAGE_HEIGHT = 792;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 14;

const INK = "#1a1a1f";
const MUTED = "#5a5a66";
const ACCENT = "#5b21b6";
const LINE_COLOR = "#d8d8e0";

class ReportCursor {
  doc: jsPDF;
  y = MARGIN;

  constructor(doc: jsPDF) {
    this.doc = doc;
  }

  ensureSpace(height: number) {
    if (this.y + height > PAGE_HEIGHT - MARGIN) {
      this.doc.addPage();
      this.y = MARGIN;
    }
  }

  heading(text: string) {
    this.ensureSpace(LINE_HEIGHT * 2);
    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(12);
    this.doc.setTextColor(ACCENT);
    this.doc.text(sanitizeReportText(text, 120), MARGIN, this.y);
    this.y += 6;
    this.doc.setDrawColor(LINE_COLOR);
    this.doc.line(MARGIN, this.y, PAGE_WIDTH - MARGIN, this.y);
    this.y += LINE_HEIGHT;
  }

  label(label: string, value: string) {
    this.ensureSpace(LINE_HEIGHT);
    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(9);
    this.doc.setTextColor(MUTED);
    this.doc.text(`${label}:`, MARGIN, this.y);
    this.doc.setFont("helvetica", "normal");
    this.doc.setTextColor(INK);
    this.doc.text(sanitizeReportText(value, 400), MARGIN + 120, this.y);
    this.y += LINE_HEIGHT;
  }

  paragraph(text: string, mono = false) {
    this.doc.setFont(mono ? "courier" : "helvetica", "normal");
    this.doc.setFontSize(9);
    this.doc.setTextColor(INK);
    const lines = this.doc.splitTextToSize(sanitizeReportText(text, 4000), CONTENT_WIDTH) as string[];
    for (const line of lines) {
      this.ensureSpace(LINE_HEIGHT);
      this.doc.text(line, MARGIN, this.y);
      this.y += LINE_HEIGHT - 2;
    }
    this.y += 4;
  }

  row(cells: string[], widths: number[], bold = false) {
    this.ensureSpace(LINE_HEIGHT);
    this.doc.setFont("helvetica", bold ? "bold" : "normal");
    this.doc.setFontSize(8.5);
    this.doc.setTextColor(bold ? MUTED : INK);
    let x = MARGIN;
    cells.forEach((cell, i) => {
      this.doc.text(sanitizeReportText(cell, 200), x, this.y);
      x += widths[i];
    });
    this.y += LINE_HEIGHT - 2;
  }

  spacer(height = 8) {
    this.y += height;
  }
}

function eventTimestamp(events: ExecutionEvent[], eventType: string): string | null {
  const match = events.find((event) => event.event_type === eventType);
  return match ? new Date(match.created_at).toLocaleString() : null;
}

/**
 * `doc` is injectable so tests can spy on a real jsPDF instance's own
 * methods (jsPDF assigns them per-instance, not on the prototype) without
 * touching production call sites, which all rely on the default.
 */
export function buildExecutionReportPdf(
  input: ExecutionReportInput,
  doc: jsPDF = new jsPDF({ unit: "pt", format: "letter" })
): jsPDF {
  const cursor = new ReportCursor(doc);
  const generatedAt = input.generatedAt ?? new Date();
  const state = toExecutionState(input.run.status);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(INK);
  doc.text("Forge AI — Execution Report", MARGIN, cursor.y);
  cursor.y += 20;
  doc.setDrawColor(ACCENT);
  doc.setLineWidth(1.5);
  doc.line(MARGIN, cursor.y, PAGE_WIDTH - MARGIN, cursor.y);
  doc.setLineWidth(1);
  cursor.y += LINE_HEIGHT + 6;

  cursor.label("Generated", generatedAt.toLocaleString());
  cursor.label("Generated by", input.actor ? `${input.actor.display_name} (${input.actor.email})` : "Unknown actor");
  cursor.label("Run ID", input.run.id);
  cursor.label("Tenant / workspace", `${input.run.tenant_id} / ${input.run.workspace_id}`);
  cursor.spacer(10);

  cursor.heading("Run summary");
  cursor.label("Objective", input.run.objective);
  cursor.label("Workflow", input.run.workflow_name);
  cursor.label("Status", `${STATE_LABEL[state]} (raw: ${input.run.status})`);
  cursor.label("Engine", `${input.run.engine_kind} · ${input.run.engine_version}`);
  cursor.label("Version", String(input.run.version));
  const startedAt = eventTimestamp(input.events, "run.created");
  const endedAt =
    eventTimestamp(input.events, "run.succeeded") ??
    eventTimestamp(input.events, "run.failed") ??
    eventTimestamp(input.events, "run.cancelled");
  if (startedAt) cursor.label("Started at", startedAt);
  if (endedAt) cursor.label("Ended at", endedAt);
  const rootEvent = input.events.find((event) => event.event_type === "run.created");
  if (rootEvent) cursor.label("Trace / correlation ID", rootEvent.correlation_id);
  cursor.spacer(10);

  cursor.heading(`Tasks (${input.tasks.length})`);
  if (input.tasks.length === 0) {
    cursor.paragraph("No tasks recorded.");
  } else {
    cursor.row(["Step", "Name", "Kind", "Status"], [90, 210, 90, 90], true);
    for (const task of input.tasks) {
      cursor.row(
        [task.step_key, task.name, task.kind, STATE_LABEL[toExecutionState(task.status)]],
        [90, 210, 90, 90]
      );
    }
  }
  cursor.spacer(10);

  cursor.heading(`Tool actions (${input.toolInvocations.length})`);
  if (input.toolInvocations.length === 0) {
    cursor.paragraph("No tool invocations recorded.");
  } else {
    cursor.row(["Tool", "Status", "Risk", "Action hash"], [180, 90, 90, 120], true);
    for (const invocation of input.toolInvocations) {
      cursor.row(
        [
          `${invocation.tool_name} v${invocation.tool_version}`,
          invocation.status,
          invocation.risk,
          invocation.action_hash.slice(0, 16)
        ],
        [180, 90, 90, 120]
      );
      if (invocation.error_type) {
        cursor.paragraph(`  ${invocation.error_type}: ${invocation.error_message ?? "no further detail"}`);
      }
    }
  }
  cursor.spacer(10);

  cursor.heading(`Human approval decisions (${input.approvals.length})`);
  if (input.approvals.length === 0) {
    cursor.paragraph("No approval requests were required for this run.");
  } else {
    for (const approval of input.approvals) {
      cursor.label("Status", `${approval.status} (risk: ${approval.risk})`);
      cursor.label("Reason required", approval.reason);
      cursor.label("Action hash", approval.action_hash);
      if (approval.decided_by) cursor.label("Decided by", approval.decided_by);
      if (approval.decision_reason) cursor.label("Decision reason", approval.decision_reason);
      cursor.paragraph(`Action: ${JSON.stringify(approval.action_summary)}`, true);
      cursor.spacer(6);
    }
  }
  cursor.spacer(4);

  cursor.heading(`Evidence provenance (${input.evidenceItems.length})`);
  if (input.evidenceItems.length === 0) {
    cursor.paragraph("No evidence items were recorded for this run.");
  } else {
    for (const item of input.evidenceItems) {
      cursor.label("Source", `${item.source_name} (${item.source_type})`);
      cursor.label("Trust label", item.trust_label);
      cursor.label("Content hash", item.content_hash);
      cursor.paragraph(`Summary: ${JSON.stringify(item.summary)}`, true);
      cursor.spacer(6);
    }
  }
  cursor.spacer(4);

  if (input.agentIterations.length > 0) {
    cursor.heading(`Agent outcomes (${input.agentIterations.length} iterations)`);
    cursor.row(["Iteration", "Decision", "Status"], [90, 150, 150], true);
    for (const iteration of input.agentIterations) {
      cursor.row(
        [String(iteration.iteration_number), iteration.decision_type, iteration.decision_status],
        [90, 150, 150]
      );
      if (iteration.validation_errors.length > 0) {
        cursor.paragraph(`  Validation errors: ${iteration.validation_errors.join("; ")}`);
      }
    }
    const latestBudgets = budgetRowsFromIteration(input.agentIterations[input.agentIterations.length - 1]);
    if (latestBudgets.length > 0) {
      cursor.spacer(6);
      cursor.label("Iteration budget", `${latestBudgets[0].used} / ${latestBudgets[0].max}`);
      for (const row of latestBudgets.slice(1)) {
        cursor.label(row.label, `${row.used} / ${row.max}`);
      }
    }
    cursor.spacer(10);
  }

  cursor.heading("Final outcome");
  cursor.paragraph(
    state === "success"
      ? "This run completed successfully. All executed tasks reached a terminal succeeded state."
      : state === "failure"
        ? "This run failed. See task and tool sections above for the point of failure."
        : state === "cancelled"
          ? "This run was cancelled before completion."
          : "This run has not reached a terminal state; the data above reflects its status at export time."
  );

  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(
      `Forge AI execution report — run ${input.run.id} — page ${page} of ${pageCount}`,
      MARGIN,
      PAGE_HEIGHT - 24
    );
  }

  return doc;
}

/**
 * Builds the report and triggers a browser download. This is the only
 * DOM-dependent entry point — `buildExecutionReportPdf` above stays a pure
 * function so it can be unit tested without a browser.
 */
export function downloadExecutionReportPdf(input: ExecutionReportInput): void {
  const doc = buildExecutionReportPdf(input);
  doc.save(buildReportFilename(input.run.id));
}
